version: '3.8'

services:
  # Node.js
  app:
    build: .
    container_name: sentinel_api
    restart: always
    environment:
      - DATABASE_URL=postgresql://admin:admin@database:5432/sentinel?schema=public
    depends_on:
      - database
    networks:
      - sentinel-net

  # Proxy Nginx
  proxy:
    image: nginx:alpine
    container_name: sentinel_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - sentinel-net

  # Banco de Dados
  database:
    image: postgres:15-alpine
    container_name: sentinel_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=sentinel
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sentinel-net

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: sentinel_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - sentinel-net

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: sentinel_grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - sentinel-net

volumes:
  pgdata:
  grafana_data:

networks:
  sentinel-net: